@backendUrl=http://127.0.0.1:7069
@frontendUrl=http://127.0.0.1:7070

### Get Home
GET {{backendUrl}}/ HTTP/1.1
Accept: application/json

### Get Backend Healthz
GET {{backendUrl}}/healthz HTTP/1.1
Accept: application/json

### Get Frontend Healthz
GET {{frontendUrl}}/api/healthz HTTP/1.1
Accept: application/json

### Register user
POST {{backendUrl}}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "test@gmail.com",
    "password": "Test@123$",
    "password_confirm": "Test@123$"
}

### Login
# @name userLogin
POST {{backendUrl}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "king.mana@gmail.com",
    "password": "Admin@123$"
}

### Save auth token
@authToken={{userLogin.response.body.token}}

### Get Users
GET {{backendUrl}}/auth/users HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Me
GET {{backendUrl}}/auth/me HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### logout
DELETE {{backendUrl}}/auth/logout HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Protected
GET {{backendUrl}}/protected HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Article
POST {{backendUrl}}/articles HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "title": "Test Article 8",
    "content": "Test Article Body eight",
    "categoryId": "6c410465-dc49-4b4c-bc01-306b3ef12cd8"
}

### Get Articles
GET {{backendUrl}}/articles HTTP/1.1
Accept: application/json

### Get Article
GET {{backendUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f HTTP/1.1
Accept: application/json

### Update Article
PUT {{backendUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "title": "Test Article updated",
     "content": "Test Article Body updated"
}

### Create Article Comment
POST {{backendUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f/comments HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
     "content": "Final dummy one!"
}

### Create Article Comment
DELETE {{backendUrl}}/articles/comments/45ffe5a4-d0e5-4fd1-bef4-d0d525b81824 HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Category
POST {{backendUrl}}/categories HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "name": "Politics",
    "description": "All about politics"
}

### Get Categories
GET {{backendUrl}}/categories HTTP/1.1
Accept: application/json
