@baseUrl=http://127.0.0.1:7069

### Get Home
GET {{baseUrl}}/ HTTP/1.1
Accept: application/json

### Get Healthz
GET {{baseUrl}}/healthz HTTP/1.1
Accept: application/json

### Register user
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Test User",
    "email": "test@gmail.com",
    "password": "Test@123$",
    "password_confirm": "Test@123$"
}

### Login
# @name userLogin
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "test@gmail.com",
    "password": "Test@123$"
}

### Save auth token
@authToken={{userLogin.response.body.token}}

### Get Users
GET {{baseUrl}}/auth/users HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Me
GET {{baseUrl}}/auth/me HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### logout
DELETE {{baseUrl}}/auth/logout HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Protected
GET {{baseUrl}}/protected HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Article
POST {{baseUrl}}/articles HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "title": "Test Article 5",
    "content": "Test Article Body Five",
    "categoryId": "6c410465-dc49-4b4c-bc01-306b3ef12cd8"
}

### Get Articles
GET {{baseUrl}}/articles HTTP/1.1
Accept: application/json

### Get Article
GET {{baseUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f HTTP/1.1
Accept: application/json

### Update Article
PUT {{baseUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "title": "Test Article updated",
     "content": "Test Article Body updated"
}

### Create Article Comment
POST {{baseUrl}}/articles/8c048069-be0c-4f22-8926-26f82677c97f/comments HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
     "content": "Final dummy one!"
}

### Create Article Comment
DELETE {{baseUrl}}/articles/comments/45ffe5a4-d0e5-4fd1-bef4-d0d525b81824 HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Category
POST {{baseUrl}}/categories HTTP/1.1
Authorization: Bearer {{authToken}}
Accept: application/json

{
    "name": "Politics",
    "description": "All about politics"
}

### Get Categories
GET {{baseUrl}}/categories HTTP/1.1
Accept: application/json
