services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - dublog_pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dublog
      - POSTGRES_USER=dublog
      - POSTGRES_DB=dublog
    networks:
      - dublog_net

volumes:
  dublog_pgdb:
  dublog_redis:

networks:
  dublog_net:
