replicaCount: 1

image:
  repository: ektowett/dublog-frontend
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true

livenessProbe:
  path: /api/healthz
  port: 7070
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 15

readinessProbe:
  path: /api/healthz
  port: 7070
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 15

containerPort: 7070

service:
  type: ClusterIP
  port: 7070

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  hosts:
    - host: stage-dublog.citizix.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dublog-tls
      hosts:
        - stage-dublog.citizix.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

env:
  ENV: stage
  AUTH_SECRET: fb98baee7dab4ca9ae75750008479f368081acd8560858a260b53ca5c46358d8
  API_URL: https://stage-dublog-api.citizix.com
  AUTH_URL: https://stage-dublog.citizix.com/api/auth
